/// Flutter icons LivecomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LivecomIcons
///      fonts:
///       - asset: fonts/LivecomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LivecomIcons {
  LivecomIcons._();

  static const _kFontFam = 'LivecomIcons';
  static const String _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdraw =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__stroke_ask =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stream =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
